name: whatsapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  firebase_storage: ^11.0.2
  cloud_firestore: ^4.0.2
  country_picker: ^2.0.16
  flutter_riverpod: ^2.0.2
  image_picker: ^0.8.6
  json_serializable: ^6.5.4
  flutter_contacts: ^1.1.5+1
  intl: ^0.18.0
  shared_preferences: ^2.0.18
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  equatable: ^2.0.5
  uuid: ^3.0.7
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  cached_video_player: ^2.0.4
  camera: ^0.10.5+2
  video_player: ^2.6.0
  path_provider: ^2.0.15
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  freezed: ^2.3.4

flutter:
  uses-material-design: true

  assets:
    - lib/core/resources/assets/images/
