name: whatsapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.1.0
  firebase_auth: ^4.0.2
  firebase_storage: ^11.0.2
  cloud_firestore: ^4.0.2
  country_picker: ^2.0.16
  flutter_riverpod: ^2.0.2
  image_picker: ^0.8.6
  json_serializable: ^6.5.4
  flutter_contacts: ^1.1.5+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/splash_icon.png
    - assets/images/meta_logo.png
    - assets/images/bg.png
